### ISSUE TITLE
Prevent passwords from being exposed

### ISSUE THREAD

**Issue by netromdk** [garvinguan/emacs-one-time-pad#4]
I think it's a neat package you've created.

One thing I noticed is that since I have `savehist` enabled the passwords used are stored like this:

``` elisp
(setq minibuffer-history '("thisisanawesometest" "thisisatest" ...)
```

This defeats the purpose of encryption if you can read them in plaintext.

Maybe you could read the values in some other manner or disabling the value from being remembered in the minibuffer history.

**Comment by garvinguan** [comment]
Good suggestion, let me look into it!

**Comment by garvinguan** [comment]
I changed read-string to read-passwd so the key shouldn't be visible in the history and when you type it. Though this might be slightly more inconvenient when typing the key, this should be a step in the right direction.

**Comment by garvinguan** [comment]
In the mean time I'll find a solution (writing another function probably) where you can see what you type but won't be saved in minibuffer history

**Comment by garvinguan** [comment]
I created another function which takes input like so 

```
(let ((minibuffer-history minibuffer-history)) (read-string "Key to use: "))
```

to prevent the input being stored in the minibuffer-history. Let me know what you think!

**Comment by netromdk** [comment]
That's a nice solution. By the way, instead of duplicating the function for your `-hide-key` variant you could just call a "private" function from both of them.

**Comment by garvinguan** [comment]
Great tip, I've moved the overlapping code into a private function. I didn't know you could hide functions like that! Thanks (I'm still reading Emacs Lisp Intro inside Emacs haha)

**Comment by netromdk** [comment]
You're welcome :)
